import { Country } from "@/interfaces"

export const countries: Country[] = [
	{
		name: "China",
		localName: "中国",
		phoneExtension: "+86",
		countrySuffix: "cn",
		flagUrl: "https://flagcdn.com/w320/cn.png",
	},
	{
		name: "Germany",
		localName: "Deutschland",
		phoneExtension: "+49",
		countrySuffix: "de",
		flagUrl: "https://flagcdn.com/w320/de.png",
	},
	{
		name: "United Kingdom",
		localName: "United Kingdom",
		phoneExtension: "+44",
		countrySuffix: "gb",
		flagUrl: "https://flagcdn.com/w320/gb.png",
	},
	{
		name: "Netherlands",
		localName: "Nederland",
		phoneExtension: "+31",
		countrySuffix: "nl",
		flagUrl: "https://flagcdn.com/w320/nl.png",
	},
	{
		name: "Russia",
		localName: "Россия",
		phoneExtension: "+7",
		countrySuffix: "ru",
		flagUrl: "https://flagcdn.com/w320/ru.png",
	},
	{
		name: "Brazil",
		localName: "Brasil",
		phoneExtension: "+55",
		countrySuffix: "br",
		flagUrl: "https://flagcdn.com/w320/br.png",
	},
	{
		name: "France",
		localName: "France",
		phoneExtension: "+33",
		countrySuffix: "fr",
		flagUrl: "https://flagcdn.com/w320/fr.png",
	},
	{
		name: "Colombia",
		localName: "Colombia",
		phoneExtension: "+57",
		countrySuffix: "co",
		flagUrl: "https://flagcdn.com/w320/co.png",
	},
	{
		name: "Canada",
		localName: "Canada",
		phoneExtension: "+1",
		countrySuffix: "ca",
		flagUrl: "https://flagcdn.com/w320/ca.png",
	},
	{
		name: "United States",
		localName: "United States",
		phoneExtension: "+1",
		countrySuffix: "us",
		flagUrl: "https://flagcdn.com/w320/us.png",
	},
	{
		name: "India",
		localName: "भारत",
		phoneExtension: "+91",
		countrySuffix: "in",
		flagUrl: "https://flagcdn.com/w320/in.png",
	},
	{
		name: "Japan",
		localName: "日本",
		phoneExtension: "+81",
		countrySuffix: "jp",
		flagUrl: "https://flagcdn.com/w320/jp.png",
	},
	{
		name: "Mexico",
		localName: "México",
		phoneExtension: "+52",
		countrySuffix: "mx",
		flagUrl: "https://flagcdn.com/w320/mx.png",
	},
	{
		name: "Australia",
		localName: "Australia",
		phoneExtension: "+61",
		countrySuffix: "au",
		flagUrl: "https://flagcdn.com/w320/au.png",
	},
	{
		name: "Italy",
		localName: "Italia",
		phoneExtension: "+39",
		countrySuffix: "it",
		flagUrl: "https://flagcdn.com/w320/it.png",
	},
	{
		name: "Spain",
		localName: "España",
		phoneExtension: "+34",
		countrySuffix: "es",
		flagUrl: "https://flagcdn.com/w320/es.png",
	},
	{
		name: "South Korea",
		localName: "대한민국",
		phoneExtension: "+82",
		countrySuffix: "kr",
		flagUrl: "https://flagcdn.com/w320/kr.png",
	},
	{
		name: "Indonesia",
		localName: "Indonesia",
		phoneExtension: "+62",
		countrySuffix: "id",
		flagUrl: "https://flagcdn.com/w320/id.png",
	},
	{
		name: "Turkey",
		localName: "Türkiye",
		phoneExtension: "+90",
		countrySuffix: "tr",
		flagUrl: "https://flagcdn.com/w320/tr.png",
	},
	{
		name: "Vietnam",
		localName: "Việt Nam",
		phoneExtension: "+84",
		countrySuffix: "vn",
		flagUrl: "https://flagcdn.com/w320/vn.png",
	},
	{
		name: "Poland",
		localName: "Polska",
		phoneExtension: "+48",
		countrySuffix: "pl",
		flagUrl: "https://flagcdn.com/w320/pl.png",
	},
	{
		name: "Thailand",
		localName: "ประเทศไทย",
		phoneExtension: "+66",
		countrySuffix: "th",
		flagUrl: "https://flagcdn.com/w320/th.png",
	},
	{
		name: "Argentina",
		localName: "Argentina",
		phoneExtension: "+54",
		countrySuffix: "ar",
		flagUrl: "https://flagcdn.com/w320/ar.png",
	},
	{
		name: "South Africa",
		localName: "South Africa",
		phoneExtension: "+27",
		countrySuffix: "za",
		flagUrl: "https://flagcdn.com/w320/za.png",
	},
	{
		name: "Ukraine",
		localName: "Україна",
		phoneExtension: "+380",
		countrySuffix: "ua",
		flagUrl: "https://flagcdn.com/w320/ua.png",
	},
	{
		name: "Malaysia",
		localName: "Malaysia",
		phoneExtension: "+60",
		countrySuffix: "my",
		flagUrl: "https://flagcdn.com/w320/my.png",
	},
	{
		name: "Philippines",
		localName: "Pilipinas",
		phoneExtension: "+63",
		countrySuffix: "ph",
		flagUrl: "https://flagcdn.com/w320/ph.png",
	},
	{
		name: "Sweden",
		localName: "Sverige",
		phoneExtension: "+46",
		countrySuffix: "se",
		flagUrl: "https://flagcdn.com/w320/se.png",
	},
	{
		name: "Belgium",
		localName: "België",
		phoneExtension: "+32",
		countrySuffix: "be",
		flagUrl: "https://flagcdn.com/w320/be.png",
	},
	{
		name: "Switzerland",
		localName: "Schweiz",
		phoneExtension: "+41",
		countrySuffix: "ch",
		flagUrl: "https://flagcdn.com/w320/ch.png",
	},
	{
		name: "Saudi Arabia",
		localName: "المملكة العربية السعودية",
		phoneExtension: "+966",
		countrySuffix: "sa",
		flagUrl: "https://flagcdn.com/w320/sa.png",
	},
	{
		name: "Egypt",
		localName: "مصر",
		phoneExtension: "+20",
		countrySuffix: "eg",
		flagUrl: "https://flagcdn.com/w320/eg.png",
	},
	{
		name: "Portugal",
		localName: "Portugal",
		phoneExtension: "+351",
		countrySuffix: "pt",
		flagUrl: "https://flagcdn.com/w320/pt.png",
	},
	{
		name: "Greece",
		localName: "Ελλάδα",
		phoneExtension: "+30",
		countrySuffix: "gr",
		flagUrl: "https://flagcdn.com/w320/gr.png",
	},
	{
		name: "Norway",
		localName: "Norge",
		phoneExtension: "+47",
		countrySuffix: "no",
		flagUrl: "https://flagcdn.com/w320/no.png",
	},
	{
		name: "Denmark",
		localName: "Danmark",
		phoneExtension: "+45",
		countrySuffix: "dk",
		flagUrl: "https://flagcdn.com/w320/dk.png",
	},
	{
		name: "Finland",
		localName: "Suomi",
		phoneExtension: "+358",
		countrySuffix: "fi",
		flagUrl: "https://flagcdn.com/w320/fi.png",
	},
	{
		name: "Austria",
		localName: "Österreich",
		phoneExtension: "+43",
		countrySuffix: "at",
		flagUrl: "https://flagcdn.com/w320/at.png",
	},
	{
		name: "Ireland",
		localName: "Éire",
		phoneExtension: "+353",
		countrySuffix: "ie",
		flagUrl: "https://flagcdn.com/w320/ie.png",
	},
	{
		name: "New Zealand",
		localName: "Aotearoa",
		phoneExtension: "+64",
		countrySuffix: "nz",
		flagUrl: "https://flagcdn.com/w320/nz.png",
	},
	{
		name: "Czech Republic",
		localName: "Česká republika",
		phoneExtension: "+420",
		countrySuffix: "cz",
		flagUrl: "https://flagcdn.com/w320/cz.png",
	},
	{
		name: "Hungary",
		localName: "Magyarország",
		phoneExtension: "+36",
		countrySuffix: "hu",
		flagUrl: "https://flagcdn.com/w320/hu.png",
	},
	{
		name: "Romania",
		localName: "România",
		phoneExtension: "+40",
		countrySuffix: "ro",
		flagUrl: "https://flagcdn.com/w320/ro.png",
	},
	{
		name: "Slovakia",
		localName: "Slovensko",
		phoneExtension: "+421",
		countrySuffix: "sk",
		flagUrl: "https://flagcdn.com/w320/sk.png",
	},
	{
		name: "Bulgaria",
		localName: "България",
		phoneExtension: "+359",
		countrySuffix: "bg",
		flagUrl: "https://flagcdn.com/w320/bg.png",
	},
	{
		name: "Serbia",
		localName: "Србија",
		phoneExtension: "+381",
		countrySuffix: "rs",
		flagUrl: "https://flagcdn.com/w320/rs.png",
	},
	{
		name: "Slovenia",
		localName: "Slovenija",
		phoneExtension: "+386",
		countrySuffix: "si",
		flagUrl: "https://flagcdn.com/w320/si.png",
	},
	{
		name: "Croatia",
		localName: "Hrvatska",
		phoneExtension: "+385",
		countrySuffix: "hr",
		flagUrl: "https://flagcdn.com/w320/hr.png",
	},
	{
		name: "Lithuania",
		localName: "Lietuva",
		phoneExtension: "+370",
		countrySuffix: "lt",
		flagUrl: "https://flagcdn.com/w320/lt.png",
	},
	{
		name: "Latvia",
		localName: "Latvija",
		phoneExtension: "+371",
		countrySuffix: "lv",
		flagUrl: "https://flagcdn.com/w320/lv.png",
	},
	{
		name: "Estonia",
		localName: "Eesti",
		phoneExtension: "+372",
		countrySuffix: "ee",
		flagUrl: "https://flagcdn.com/w320/ee.png",
	},
	{
		name: "Iceland",
		localName: "Ísland",
		phoneExtension: "+354",
		countrySuffix: "is",
		flagUrl: "https://flagcdn.com/w320/is.png",
	},
	{
		name: "Luxembourg",
		localName: "Lëtzebuerg",
		phoneExtension: "+352",
		countrySuffix: "lu",
		flagUrl: "https://flagcdn.com/w320/lu.png",
	},
	{
		name: "Malta",
		localName: "Malta",
		phoneExtension: "+356",
		countrySuffix: "mt",
		flagUrl: "https://flagcdn.com/w320/mt.png",
	},
	{
		name: "Cyprus",
		localName: "Κύπρος",
		phoneExtension: "+357",
		countrySuffix: "cy",
		flagUrl: "https://flagcdn.com/w320/cy.png",
	},
	{
		name: "Lebanon",
		localName: "لبنان",
		phoneExtension: "+961",
		countrySuffix: "lb",
		flagUrl: "https://flagcdn.com/w320/lb.png",
	},
	{
		name: "United Arab Emirates",
		localName: "الإمارات العربية المتحدة",
		phoneExtension: "+971",
		countrySuffix: "ae",
		flagUrl: "https://flagcdn.com/w320/ae.png",
	},
	{
		name: "Qatar",
		localName: "قطر",
		phoneExtension: "+974",
		countrySuffix: "qa",
		flagUrl: "https://flagcdn.com/w320/qa.png",
	},
	{
		name: "Kuwait",
		localName: "الكويت",
		phoneExtension: "+965",
		countrySuffix: "kw",
		flagUrl: "https://flagcdn.com/w320/kw.png",
	},
	{
		name: "Bahrain",
		localName: "البحرين",
		phoneExtension: "+973",
		countrySuffix: "bh",
		flagUrl: "https://flagcdn.com/w320/bh.png",
	},
	{
		name: "Jordan",
		localName: "الأردن",
		phoneExtension: "+962",
		countrySuffix: "jo",
		flagUrl: "https://flagcdn.com/w320/jo.png",
	},
	{
		name: "Pakistan",
		localName: "پاکستان",
		phoneExtension: "+92",
		countrySuffix: "pk",
		flagUrl: "https://flagcdn.com/w320/pk.png",
	},
	{
		name: "Bangladesh",
		localName: "বাংলাদেশ",
		phoneExtension: "+880",
		countrySuffix: "bd",
		flagUrl: "https://flagcdn.com/w320/bd.png",
	},
	{
		name: "Nigeria",
		localName: "Nigeria",
		phoneExtension: "+234",
		countrySuffix: "ng",
		flagUrl: "https://flagcdn.com/w320/ng.png",
	},
	{
		name: "Kenya",
		localName: "Kenya",
		phoneExtension: "+254",
		countrySuffix: "ke",
		flagUrl: "https://flagcdn.com/w320/ke.png",
	},
]
